version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: revendamais-app
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: revendamais-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: revenda-mais
            MYSQL_USER: revenda-user
            MYSQL_PASSWORD: revenda-senha
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: revendamais-nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: revendamais-redis
        ports:
            - '6382:6379'
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
